### ISSUE TITLE
Proof test vector verifiability

### ISSUE THREAD

**Issue by clehner** [uport-project/ethereum-eip712-signature-2021-spec#11]
I'm unable to verify the current test vector proof example 5:
- The proof `eip712Domain` object is missing the required `domain` property.
- The proof `created` date does not match the `created` date of the unsigned proof in the preceding examples.

I would like to use the test vector to test this implementation https://github.com/spruceid/ssi/pull/213.
Is there more info that could be added to enable verification of the proof? Or if it is not meant to be verifiable (given it is labeled non-normative), could it be replaced with one that is verifiable?
It would be useful for testing if it could be verified with the `TypedData` and issuer keypair in the preceding examples.

**Comment by mirceanis** [comment]
Thanks for spotting this, @clehner
I think the test vector should be replaced if the current one is broken.
Would you be willing to contribute a PR with a replacement?

**Comment by clehner** [comment]
@mirceanis yes, I'll try to do that later this week.

**Comment by clehner** [comment]
@mirceanis
A candidate replacement test vector is in https://github.com/uport-project/ethereum-eip712-signature-2021-spec/pull/14. Can you verify it?
